# Makefile for AIX 4.3 & OpenLDAP 2.x

# Copyright (C) 1997 Luke Howard.
# This file is part of the nss_ldap Library.

# The nss_ldap library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.

# The nss_ldap Library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.

# You should have received a copy of the GNU Library General Public
# License along with the nss_ldap Library; see the file COPYING.LIB.  If not,
# write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

#
# $Id$
#

MODULE=nss_ldap
PLATFORM=rs6000
HDRS=	\
	ldap-alias.h \
	ldap-ethers.h \
	ldap-grp.h \
	ldap-hosts.h \
	ldap-netgrp.h \
	ldap-network.h \
	ldap-nss.h \
	ldap-proto.h \
	ldap-pwd.h \
	ldap-rpc.h \
	ldap-service.h \
	ldap-spwd.h \
	util.h \
	globals.h \
	ltf.h \
	irs-nss.h \
	resolve.h \
	dnsconfig.h \
	snprintf.h \
	resolve.h

SRCS=	ldap-nss.c \
	ldap-pwd.c \
	ldap-grp.c \
	ldap-rpc.c \
	ldap-hosts.c \
	ldap-network.c \
	ldap-proto.c \
	ldap-spwd.c \
	ldap-alias.c \
	ldap-service.c \
	ldap-ethers.c \
	ldap-bp.c \
	irs-nss.c \
	util.c \
	ltf.c \
	snprintf.c \
	resolve.c \
	dnsconfig.c \
	globals.c

OBJS=${SRCS:.c=.o}

LIB=${MODULE}.so

# uncomment NSFLAGS if you are using the Netscape SDK
#NSFLAGS=-I/usr/local/ldapsdk/include -DLDAP_VERSION3_API -DNETSCAPE_API_EXTENSIONS -DRFC2307BIS -DSSL

# uncomment BSDFLAGS if you are building this as part of the BIND IRS
BSDFLAGS=-DIRS_NSS 

#BIND=../../../src/bind/src

#INCDIRS=-I/usr/local/include -I. -I${BIND}/port/linux/include -I${BIND}/include -I${BIND}/lib/irs -I${BIND}/port/${PLATFORM}/include
INCDIRS=-I/usr/local/include -I.

#LIBDIRS=-L/usr/local/ldapsdk/lib
#LIBS=-lldapssl30
LIBDIRS=-L/usr/local/lib
LIBS=-lldap -llber -lsasl -lssl -lcrypto -lpthreads
WARNINGS =  -Wwrite-strings \
	-Wpointer-arith -Wcast-qual -Wcast-align \
	-Wtraditional -Wstrict-prototypes -Wmissing-prototypes \
	-Wnested-externs -Winline -Wshadow -pedantic

CC=cc
COMPILERFLAGS=-g -D_THREAD_SAFE -DAIX_IRS -DLDAP_VERSION3_API -DHAVE_LDAP_LD_FREE -DWANT_IRS_PW -DBIND_TIMEOUT=2 ${INCDIRS}

CFLAGS= -DLDAP_REFERRALS ${NSFLAGS} ${SUNFLAGS} ${BSDFLAGS} ${GNUFLAGS} ${COMPILERFLAGS} ${INCDIRS}

all: ${MODULE} install

${MODULE}: ${OBJS}
	$(CC) -bM:SRE -g -o ${LIB} ${OBJS} -bnoentry -bE:exports.aix ${LIBDIRS} ${LIBS} -lc

install:

clean:
	rm -f ${OBJS} ${LIB}

test: test.c ${LIB}
	$(CC) -L. ${BSDFLAGS} ${COMPILERFLAGS} ${INCDIRS} \
		-brtl -o test test.c ${LIB} -lpthreads

#-lbind
